version: 2.1

workflows:
    test-deploy:
        jobs:
            - test

jobs:
    test:
        docker:
            - image: cimg/node:18.16
        steps:
            - checkout
            - run: node --version
