version: 2.1

orbs:
  node: circleci/node@5.1.0

workflows:
  test-deploy:
    jobs:
      - clone
      - sayhello
      - test:
          requires:
            - clone
            - sayhi
      - sayhi:
          context:
          - test_context
          requires:
            - sayhello
          filters:
            branches:
              only:
                - main

jobs:
  test:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - node/install-packages:
          cache-path: node_modules
      - run:
          name: un My Tests
          command: yarn jest --ci --reporters=default --reporters=jest-junit
      - run:
          name: Copy tests results for storing
          command: |
            mkdir test-results
            cp junit.xml test-results/
          when: always
          
      - store_test_results:
          path: ~/test-results

  sayhello:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: 'Say Hello'
          command: 'echo Say Hello Required to say Hi'

  sayhi:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run: echo $IS_RAINING 
      - run:
          name: 'Say Hi'
          command: 'echo Say Hi'
      - run:
          name: 'Print context value'
          command: echo $IS_RAINING 
  clone:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "be:fc:d8:df:94:f8:d4:28:61:80:10:8c:6c:eb:83:b4"
      - run:
          name: Clone Repository
          command: git clone git@github.com:paulinahry/allison_band.git
