version: 2.1

orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.4.0
  snyk: snyk/snyk@2.0.2

workflows:
  test-deploy:
    jobs:
      - clone
      - sayhello
      - build_and_test:
          requires:
            - clone
            - sayhi
      - snyk_scan:
          context:
            - docker_login_context
      - sayhi:
          context:
            - test_context
          requires:
            - sayhello
          filters:
            branches:
              only:
                - main
      - build_image_push:
          requires:
            - build_and_test
            - snyk_scan
          context:
            - docker_login_context

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - node/install-packages:
          cache-path: node_modules
      - run:
          name: Run My Tests
          command: yarn jest --ci --reporters=default --reporters=jest-junit
      - run:
          name: Copy tests results for storing
          command: |
            mkdir test-results
            cp junit.xml test-results/
          when: always
      - store_test_results:
          path: test-results

  build_image_push:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to Docker Hub
          command: echo $PASS_DOCKER | docker login -u $USERNAME_DOCKER --password-stdin
      - docker/check
      - run:
          name: Debug
          command: 'echo $USERNAME_DOCKER, $PASS_DOCKER'
      - run:
          name: Build 
          command: docker push $USERNAME_DOCKER/$REPO_DOCKER
      - run:
          name: Push to Docker Hub
          command: docker push $USERNAME_DOCKER/$REPO_DOCKER

  snyk_scan:
    docker:
      - image: cimg/node:18.16
    steps:
    - checkout:
    - node/install-packages
    - snyk/scan:
        fail-on-issues: false
        monitor-on-build: false
  sayhello:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: 'Say Hello'
          command: 'echo Say Hello Required to say Hi'

  sayhi:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run: echo $IS_RAINING 
      - run:
          name: 'Say Hi'
          command: 'echo Say Hi'
      - run:
          name: 'Print context value'
          command: echo $IS_RAINING 

  clone:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "be:fc:d8:df:94:f8:d4:28:61:80:10:8c:6c:eb:83:b4"
      - run:
          name: Clone Repository
          command: git clone git@github.com:paulinahry/allison_band.git
