const tour = [
    {
        id: 1,
        town: 'Marseille',
        country: 'France',
        date: new Date(2023, 3, 1),
        place: 'Summer Paradise Club',
        tickets: 'https://www.eventbrite.com/',
    },
    {
        id: 2,
        town: 'Paris',
        country: 'France',
        date: new Date(2023, 6, 11),
        place: 'Rester',
        tickets: 'https://www.eventbrite.com/',
    },
    {
        id: 3,
        town: 'Lyon',
        country: 'France',
        date: new Date(2023, 6, 12),
        place: 'Non Club',
        tickets: 'https://www.eventbrite.com/',
    },
    {
        id: 4,
        town: 'Toulouse',
        country: 'France',
        date: new Date(2023, 6, 13),
        place: 'Oui',
        tickets: 'https://www.eventbrite.com/',
    },
    {
        id: 5,
        town: 'Nice',
        country: 'France',
        date: new Date(2023, 6, 14),
        place: 'Garçon',
    },
    {
        id: 6,
        town: 'Nantes',
        country: 'France',
        date: new Date(2023, 6, 16),
        place: 'Au revoir',
        tickets: 'https://www.eventbrite.com/',
    },
    {
        id: 7,
        town: 'Montpellier',
        country: 'France',
        date: new Date(2023, 6, 19),
        place: 'Bonheur',
        tickets: 'https://www.eventbrite.com/',
    },
    {
        id: 8,
        town: 'Bordeaux',
        country: 'France',
        date: new Date(2023, 6, 30),
        place: 'Sourire',
        tickets: 'https://www.eventbrite.com/',
    },
    {
        id: 9,
        town: 'Hamburg',
        country: 'Germany',
        date: new Date(2023, 7, 2),
        place: 'Amour',
    },
]

export default tour
